In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import os
from pathlib import Path
from tqdm import tqdm
import matplotlib.pyplot as plt
import random

In [3]:
import cv2
from fastai import *
from fastai.vision import *
from fastai.callbacks import *

In [4]:
from dataset_spliter import SplitByPatient
from metrics import *#F1Weighted, MCC
from losses import *

In [5]:
path = Path('/data/Datasets/WhiteBloodCancer/train/')

In [6]:
np.random.seed(42)

In [7]:
fnames = get_image_files(path, recurse=True)
fnames[:5]

[PosixPath('/data/Datasets/WhiteBloodCancer/train/fold_1/hem/UID_H10_43_1_hem.bmp'),
 PosixPath('/data/Datasets/WhiteBloodCancer/train/fold_1/hem/UID_H22_31_15_hem.bmp'),
 PosixPath('/data/Datasets/WhiteBloodCancer/train/fold_1/hem/UID_H14_9_11_hem.bmp'),
 PosixPath('/data/Datasets/WhiteBloodCancer/train/fold_1/hem/UID_H14_28_6_hem.bmp'),
 PosixPath('/data/Datasets/WhiteBloodCancer/train/fold_1/hem/UID_H10_189_1_hem.bmp')]

In [8]:
hem_regex = re.compile(r'UID_(H[0-9]+)_', re.IGNORECASE)
all_regex = re.compile(r'UID_([0-9]+)_', re.IGNORECASE)

In [9]:
hem_patient_ids = list(set([hem_regex.search(str(fn)).group(1)
                            for fn in fnames if hem_regex.search(str(fn)) is not None]))
all_patint_ids = list(set([all_regex.search(str(fn)).group(1)
                           for fn in fnames if all_regex.search(str(fn)) is not None]))

hem_patients = dict((k,[]) for k in hem_patient_ids)
all_patints = dict((k,[]) for k in all_patint_ids)

[all_patints[key].append(fn) for key in all_patints.keys() for fn in fnames if 'UID_{0}_'.format(key) in str(fn)]
[hem_patients[key].append(fn) for key in hem_patients.keys() for fn in fnames if 'UID_{0}_'.format(key) in str(fn)]
print()

## Split data into train val 

In [10]:
split_handler = SplitByPatient(hem_patients, all_patints)

### Split by regex

In [11]:
train_regex = re.compile(r'(fold_0|fold_1|fold_2)')
val_regex = re.compile(r'(fold_3)')

hem_train, all_train, hem_val, all_val = split_handler.split_by_regex(train_regex, val_regex)

In [12]:
print('Train Total: {0}'.format(len(hem_train)+len(all_train)))
print('Val Total: {0}'.format(len(hem_val)+len(all_val)))
print("")
print('Hem train: {}'.format(len(hem_train)))
print('All train: {}'.format(len(all_train)))
print('Hem val: {}'.format(len(hem_val)))
print('All val: {}'.format(len(all_val)))

Train Total: 10661
Val Total: 1867

Hem train: 3389
All train: 7272
Hem val: 648
All val: 1219


In [13]:
pat = re.compile(r'^.*(hem|all).bmp$')

def get_label(fn):
    return pat.search(str(fn)).group(1)

### Use complete image

In [14]:
train = ImageList(hem_train + all_train) #optinal scale up classes 
valid = ImageList(hem_val + all_val)

In [15]:
item_list = ItemLists(path, train, valid)
lls = item_list.label_from_func(get_label).add_test_folder('../test')

#### Data augmentation

In [16]:
xtra_tfms=[cutout(n_holes=5, length=0.2)]#squish(scale=0.66), 
tfms = get_transforms(do_flip=True, 
                      flip_vert=True, 
                      #max_rotate=90,  
                      max_lighting=0.05, 
                      max_zoom=1.0, 
                      max_warp=0.0,
                      #p_affine=0.75,
                      #p_lighting=0.75,  
                      #xtra_tfms=xtra_tfms,
                     )

#### Create dataset 

In [17]:
def get_data(bs, size):
    data  = ImageDataBunch.create_from_ll(lls, size=size, bs=bs, 
                                      ds_tfms=tfms, padding_mode='zeros',
                                      resize_method=ResizeMethod.PAD)
    data = data.normalize()
    #data = data.normalize((channel_mean, channel_std))
    return data
    

In [18]:
size = 256
bs = 96
data = get_data(bs, size)

experiment_name = "baseline_rn50"
learn = create_cnn(data, models.resnet50, 
                       metrics=[error_rate, F1Weighted(), MCC()], #  
                       #loss_func=FocalLoss(num_classes=1),
                       #ps=0.75,
                       #wd=0.1,
                       loss_func = LabelSmoothingCrossEntropy(),
                       callback_fns=[partial(SaveModelCallback, name='stage1-{}-{}'.format(experiment_name, size))],

                  )#

/home/c.marzahl@de.eu.local/ProgProjekte/fastai_v1/fastai/fastai/vision/learner.py:93: UserWarning: `create_cnn` is deprecated and is now named `cnn_learner`.
  warn("`create_cnn` is deprecated and is now named `cnn_learner`.")


In [19]:
learn.freeze()
lr = 1e-2
learn.fit_one_cycle(5, lr)

learn.unfreeze()
learn.fit_one_cycle(10, slice(1e-5,lr/5))

Better model found at epoch 0 with val_loss value: 0.834194004535675.
Better model found at epoch 1 with val_loss value: 0.7763753533363342.
Better model found at epoch 2 with val_loss value: 0.6458670496940613.
Better model found at epoch 4 with val_loss value: 0.6218984723091125.


Better model found at epoch 0 with val_loss value: 0.6471847295761108.
Better model found at epoch 1 with val_loss value: 0.6238506436347961.
Better model found at epoch 2 with val_loss value: 0.6161949038505554.
Better model found at epoch 4 with val_loss value: 0.607267439365387.
Better model found at epoch 5 with val_loss value: 0.6053359508514404.
Better model found at epoch 6 with val_loss value: 0.53286212682724.
Better model found at epoch 7 with val_loss value: 0.5079582929611206.


In [20]:
#learn.export('baseline_rn50-1.pkl') 

In [21]:
size = 384
bs = 32
learn.data = get_data(bs, size)

learn.freeze()
lr = 1e-2
learn.fit_one_cycle(5, lr)

learn.unfreeze()
learn.fit_one_cycle(10, slice(1e-5,lr/5))

Better model found at epoch 0 with val_loss value: 0.7313843369483948.
Better model found at epoch 1 with val_loss value: 0.6525838971138.
Better model found at epoch 2 with val_loss value: 0.5771800875663757.
Better model found at epoch 4 with val_loss value: 0.5139691829681396.


Better model found at epoch 0 with val_loss value: 0.537585437297821.
Better model found at epoch 6 with val_loss value: 0.5233539938926697.


In [22]:
#learn.export('baseline_rn50-384-2.pkl') 

In [23]:
size = 450
bs = 16
learn.data = get_data(bs, size)

learn.freeze()
lr = 1e-2
learn.fit_one_cycle(5, lr)

learn.unfreeze()
learn.fit_one_cycle(10, slice(1e-5,lr/5))

Better model found at epoch 0 with val_loss value: 2.2316102981567383.
Better model found at epoch 1 with val_loss value: 0.6795588135719299.
Better model found at epoch 3 with val_loss value: 0.6303207278251648.


Better model found at epoch 0 with val_loss value: 0.5537654757499695.
Better model found at epoch 1 with val_loss value: 0.5375993847846985.


In [24]:
#learn.export('baseline_rn50-450-2.pkl') 

In [60]:
y_pred, y_test_tta = learn.TTA(ds_type=DatasetType.Valid, scale=1.)#, beta=0.4, scale=1.3
y_pred = to_np(y_pred)

In [46]:
y_pred

array([[-5.162198, -1.490607],
       [-0.472721,  0.483008],
       [-1.09513 ,  1.097183],
       [ 0.170305, -0.110243],
       ...,
       [-0.207251,  0.269644],
       [ 1.019599, -1.076509],
       [ 0.99041 , -1.020569],
       [ 0.88745 , -0.929821]], dtype=float32)

In [31]:
preds_test, y_test=learn.get_preds(ds_type=DatasetType.Valid)
preds_test = np.argmax(torch.sigmoid(preds_test), axis=1)
f1_score(y_test, preds_test, average='weighted')

0.8371988263137253

In [39]:
temp, y_test=learn.get_preds(ds_type=DatasetType.Valid)
torch.sigmoid(temp)

tensor([[0.0036, 0.1557],
        [0.4221, 0.5946],
        [0.2340, 0.7610],
        ...,
        [0.7318, 0.2595],
        [0.7258, 0.2686],
        [0.7051, 0.2866]])

In [28]:
y_test_tta

tensor([1, 1, 1,  ..., 0, 0, 0])

In [27]:
np.argmax(y_pred, axis=1)

array([1, 1, 1, 1, ..., 1, 0, 0, 0])

In [61]:
f1_score(y_test_tta, np.argmax(y_pred, axis=1),  average='weighted') # scale=1.

0.8489361299205921

In [53]:
f1_score(y_test_tta, np.argmax(y_pred, axis=1),  average='weighted') # scale=1.05

0.853021900669273

In [55]:
f1_score(y_test_tta, np.argmax(y_pred, axis=1),  average='weighted') # scale=1.1

0.8571500797662559

In [57]:
f1_score(y_test_tta, np.argmax(y_pred, axis=1),  average='weighted') # scale=1.1

0.8542246159029407

In [58]:
y_pred

array([[-2.231739,  2.114458],
       [-0.623906,  0.434116],
       [-1.139656,  1.125034],
       [ 0.107901, -0.033532],
       ...,
       [-0.37961 ,  0.44796 ],
       [ 1.010885, -1.083084],
       [ 0.954223, -0.974958],
       [ 0.880328, -0.924473]], dtype=float32)

In [59]:
f1_score(y_test_tta, y_pred[:, 1] > 0.5,  average='weighted') # scale=1.1

0.6631191427043902